S2 us53 user view
WildCodeSchool/2022-03-php-orleans-project-paleolife pull request #141
Opened 2022-06-20 09:39 UTC by JSDerouet

2022-06-20 10:18 UTC, SkeidoK approved these changes

2022-06-20 10:29 UTC, sblondeau requested changes

2022-06-20 10:29 UTC, sblondeau commented on src/Controller/UserController.php
> +            'users' => $userRepository->findAllClient('["ROLE_CLIENT"]'),
je suis pas sûr que ce soit nécessaire, tu veux liste tous les clients là non ?

2022-06-20 10:29 UTC, sblondeau commented on templates/user/index.html.twig
> +    <a href="{{ path('app_user_new') }}">Create new</a>
trad

2022-06-20 10:29 UTC, sblondeau commented on templates/user/index.html.twig
> +{% block title %}User index{% endblock %}
trad

2022-06-20 10:55 UTC, JSDerouet commented on src/Controller/UserController.php
> +            'users' => $userRepository->findAllClient('["ROLE_CLIENT"]'),
oui mais je ne veux pas l'admin

2022-06-20 10:56 UTC, JSDerouet commented on templates/user/index.html.twig
> +    <a href="{{ path('app_user_new') }}">Create new</a>
C'est la partie ajouter

2022-06-20 13:04 UTC, baloolc submitted a review, later dismissed

2022-06-21 06:52 UTC, sblondeau requested changes

2022-06-21 14:34 UTC, baloolc approved these changes

2022-06-22 07:11 UTC, sblondeau approved these changes

2022-06-22 07:11 UTC, merged