fixRegistration
WildCodeSchool/2022-03-php-orleans-project-paleolife pull request #226
Opened 2022-07-05 14:14 UTC by JSDerouet

2022-07-05 15:07 UTC, sblondeau requested changes

2022-07-05 15:07 UTC, sblondeau commented on src/Controller/RegistrationController.php
> +            $user->setRoles(['ROLE_USER']);
pas besoin de setter le ROLE_USER puisqu'il est donné par défaut à tout nouvel User

2022-07-05 15:08 UTC, JSDerouet commented on src/Controller/RegistrationController.php
> +            $user->setRoles(['ROLE_USER']);
Justement j'ai en besoin pour l'afficher dans la vue de l'admin

2022-07-05 15:42 UTC, sblondeau requested changes

2022-07-05 15:42 UTC, sblondeau commented on src/Controller/RegistrationController.php
> +            $user->setRoles(['ROLE_USER']);
mais le simple fait de créer un new User donne le ROLE_USER ! il l'a déjà 
regarde le code du getRoles() dans User, il ajoute automatiquement le ROLE_USER en plus

2022-07-06 06:59 UTC, sblondeau approved these changes

2022-07-06 07:00 UTC, merged