create card presentation
WildCodeSchool/2022-03-php-orleans-project-paleolife pull request #26
Opened 2022-06-08 10:37 UTC by Alexis-Thibault

2022-06-08 10:39 UTC, SkeidoK submitted a review, later dismissed

2022-06-08 15:04 UTC, sblondeau requested changes

2022-06-08 15:04 UTC, sblondeau commented on templates/home/index.html.twig
> +				<img src="{{ asset('build/images/presentation.f8fb95bf.jpg') }}" class="rounded-img" alt=""/>
pas besoin du f8fb95bf

2022-06-08 15:04 UTC, sblondeau commented on templates/home/index.html.twig
> +						It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions o
c'est administratble ? si non je veux pas du Lorem mais le vrai texte

2022-06-08 15:07 UTC, Alexis-Thibault commented on templates/home/index.html.twig
> +						It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions o
Ce n'est pas administrable mais le client ne nous a pas encore donné le texte qu'il voulait mettre

2022-06-08 15:10 UTC, SkeidoK approved these changes

2022-06-08 15:18 UTC, sblondeau requested changes
image trop grosse !

2022-06-08 15:18 UTC, sblondeau commented on templates/home/index.html.twig
> +						It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions o
ok

2022-06-09 07:27 UTC, sblondeau requested changes

2022-06-09 07:27 UTC, sblondeau commented on migrations/Version20220608145527.php
> +    {
ton US ne nécessite pas de modif de la BDD, je ne devrais pas avoir de fichier de migration

2022-06-09 08:28 UTC, JSDerouet submitted a review, later dismissed

2022-06-09 10:28 UTC, sblondeau submitted a review, later dismissed

2022-06-10 07:20 UTC, merged