add crud service
WildCodeSchool/2022-03-php-orleans-project-paleolife pull request #31
Opened 2022-06-09 14:31 UTC by SkeidoK

2022-06-09 17:43 UTC, baloolc submitted a review, later dismissed

2022-06-10 06:53 UTC, sblondeau requested changes

2022-06-10 06:53 UTC, sblondeau commented on src/Form/ServiceType.php
> +            'csrf_protection' => true,
??
d'où sors tu ces options ? elles sont inutiles :/

2022-06-10 06:53 UTC, sblondeau commented on src/Form/ServiceType.php
>              ->add('photo')
si ta photo est une Url (en tout cas pour le moment), mets un UrlType et ajoute un Assert\Url dans l'entity

2022-06-10 06:56 UTC, SkeidoK commented on src/Form/ServiceType.php
> +            'csrf_protection' => true,
Je ne sais pas j'ai suivi la doc symfony

2022-06-10 06:56 UTC, SkeidoK commented on src/Form/ServiceType.php
>              ->add('photo')
D'accord

2022-06-10 07:34 UTC, sblondeau requested changes

2022-06-10 07:34 UTC, sblondeau commented on src/Entity/Service.php
> +    #[Assert\Length(max: 255)]
Assert\Url

2022-06-10 07:36 UTC, SkeidoK commented on src/Entity/Service.php
> +    #[Assert\Length(max: 255)]
PArdon je ne l'ai pas fait aussi

2022-06-10 08:06 UTC, sblondeau approved these changes

2022-06-10 08:06 UTC, merged