delete crud service
WildCodeSchool/2022-03-php-orleans-project-paleolife pull request #32
Opened 2022-06-09 14:41 UTC by SkeidoK

2022-06-09 17:41 UTC, baloolc approved these changes

2022-06-10 06:54 UTC, sblondeau requested changes

2022-06-10 06:54 UTC, sblondeau commented on templates/service/_delete_form.html.twig
>  <form method="post" action="{{ path('app_service_delete', {'id': service.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
traduction du onsubmit

2022-06-10 07:34 UTC, sblondeau approved these changes

2022-06-10 07:34 UTC, merged