S1 us16 form contact
WildCodeSchool/2022-03-php-orleans-project-paleolife pull request #33
Opened 2022-06-09 15:25 UTC by JSDerouet

2022-06-09 17:23 UTC, baloolc submitted a review, later dismissed

2022-06-10 06:59 UTC, sblondeau commented
ne passe pas github action

2022-06-10 08:00 UTC, SkeidoK reviewed
C'est Mr Miiirland

2022-06-10 08:10 UTC, sblondeau requested changes

2022-06-10 08:10 UTC, sblondeau commented on migrations/Version20220608100553.php
> +final class Version20220608100553 extends AbstractMigration
une suele migration stp

2022-06-10 08:10 UTC, sblondeau commented on src/Controller/ContactController.php
> +                ->subject('Un utilisateur vous contact')
contacte

2022-06-10 08:10 UTC, sblondeau commented on templates/email/base.html.twig
> +        {{ encore_entry_link_tags('app') }}
c'est un template d'email et du coup tu ne vas ni charger de JS, ni charger le style de base (je ne pense pas que ça fonctionne ainsi). 
tu feras pour le moment juste du style vraiment minimal (car c'est pénible de styliser les mails)

2022-06-10 08:10 UTC, sblondeau commented on templates/email/email_user_to_admin.html.twig
> +Ses coordonées sont :<br>
coordonnées

2022-06-10 08:10 UTC, sblondeau commented on templates/email/email_user_to_admin.html.twig
> +Bonjour Monsieur Mirland.
tu peux faire un minimum de html structuré par contre (h1, p, ul/li,div...) mais pas juste des br

2022-06-10 08:23 UTC, SkeidoK approved these changes

2022-06-10 09:16 UTC, sblondeau approved these changes

2022-06-10 09:16 UTC, merged