fix_responsive_client
WildCodeSchool/2022-03-php-orleans-project-paleolife pull request #349
Opened 2022-07-11 16:27 UTC by baloolc

2022-07-11 18:03 UTC, JSDerouet commented on templates/component/_navbar_client.html.twig
> +			<div class="my-2 w-25 d-none d-md-block">
quelle est cette sorcellerie?

2022-07-12 07:22 UTC, sblondeau requested changes

2022-07-12 07:22 UTC, sblondeau commented on assets/styles/client.scss
> +@media screen and (max-width: 600px){
pas de media query pour une font-size
si tu peux pas gérer avec les classes fs- de bootstrap, part sur un clamp()

2022-07-12 12:06 UTC, sblondeau approved these changes

2022-07-12 12:06 UTC, merged