testw3c
WildCodeSchool/2022-03-php-orleans-project-paleolife pull request #418
Opened 2022-07-12 14:46 UTC by Fabionic

2022-07-12 14:47 UTC, Alexis-Thibault approved these changes

2022-07-12 15:55 UTC, sblondeau requested changes

2022-07-12 15:55 UTC, sblondeau commented on templates/home/index.html.twig
> +								<a href="/contact" class="btn btn-outline-primary fs-5 fw-bold border-2 col-12 col-lg-4">
utiliser path() pour la route dans le href

2022-07-12 15:55 UTC, sblondeau commented on templates/home/index.html.twig
> +							<a href="/contact" class="btn btn-outline-primary fw-bold justify-content-end fs-5 p-2 me-4">
idem que plus haut

2022-07-13 08:14 UTC, JSDerouet approved these changes

2022-07-13 08:27 UTC, sblondeau approved these changes

2022-07-13 08:28 UTC, merged