change type question
WildCodeSchool/2022-03-php-orleans-project-paleolife pull request #439
Opened 2022-07-18 12:39 UTC by Alexis-Thibault

2022-07-18 13:15 UTC, sblondeau requested changes

2022-07-18 13:20 UTC, codelande submitted a review, later dismissed

2022-07-18 13:58 UTC, sblondeau commented on src/Entity/Service.php
> +    #[ORM\Column(type: 'string', nullable: true)]
make:migration à faire du coup

2022-07-19 07:21 UTC, sblondeau approved these changes

2022-07-19 07:21 UTC, merged