S2 us19 login
WildCodeSchool/2022-03-php-orleans-project-paleolife pull request #72
Opened 2022-06-12 23:16 UTC by JSDerouet

2022-06-13 07:27 UTC, baloolc submitted a review, later dismissed

2022-06-13 10:07 UTC, sblondeau requested changes

2022-06-14 15:00 UTC, baloolc requested changes

2022-06-14 15:00 UTC, baloolc commented on templates/login/index.html.twig
> +
espace en trop

2022-06-15 06:55 UTC, baloolc approved these changes

2022-06-15 07:01 UTC, sblondeau requested changes

2022-06-15 07:01 UTC, sblondeau commented on src/Entity/User.php
> +    #[Assert\NotBlank()]
Assert\Email

2022-06-15 07:01 UTC, sblondeau commented on src/Entity/User.php
> +    #[Assert\NotBlank()]
Asser\tLength à max 180 pour coller à ta length en DB

2022-06-15 07:01 UTC, sblondeau commented on src/Entity/User.php
> +    #[Assert\NotBlank()]
idem Assert Length 255

2022-06-15 07:32 UTC, SkeidoK approved these changes

2022-06-15 07:40 UTC, sblondeau approved these changes

2022-06-15 07:40 UTC, merged