View exercice
WildCodeSchool/2022-03-php-orleans-project-paleolife pull request #78
Opened 2022-06-14 16:10 UTC by SkeidoK

2022-06-14 18:00 UTC, JSDerouet approved these changes

2022-06-15 06:59 UTC, sblondeau requested changes

2022-06-15 06:59 UTC, sblondeau commented on migrations/Version20220614140019.php
> +        $this->addSql('CREATE TABLE exercice (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, duration DOUBLE PRECISION NOT NULL, repetition INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACT
exercise avec un S en anglais... 
à renommer partout...

2022-06-15 06:59 UTC, sblondeau commented on migrations/Version20220614141052.php
> +<?php
si

2022-06-15 06:59 UTC, sblondeau commented on src/Controller/ExerciceController.php
> +class ExerciceController extends AbstractController
à renommer partout

2022-06-15 06:59 UTC, sblondeau commented on src/DataFixtures/ExerciceFixtures.php
> +        $exercice = new Exercice();
un peu juste en fixtures, fait un array en constante avec qq données d'exercices et boucles dessus

2022-06-15 06:59 UTC, sblondeau commented on migrations/Version20220614140019.php
> +        $this->addSql('CREATE TABLE exercice (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, duration DOUBLE PRECISION NOT NULL, repetition INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACT
tu as un raccourcis dans VScode pour renommer dans plusieurs fichiers d'un coup ^^

2022-06-15 08:46 UTC, sblondeau requested changes

2022-06-15 08:46 UTC, sblondeau commented on migrations/Version20220615072619.php
> +        $this->addSql('CREATE TABLE exercice (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, duration DOUBLE PRECISION NOT NULL, repeti
exerciSe

2022-06-15 08:48 UTC, SkeidoK commented on migrations/Version20220615072619.php
> +        $this->addSql('CREATE TABLE exercice (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, duration DOUBLE PRECISION NOT NULL, repeti
Je ne l'avais pas vu après les 50 changé desolé

2022-06-15 08:53 UTC, sblondeau commented on migrations/Version20220615072619.php
> +        $this->addSql('CREATE TABLE exercise (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, duration DOUBLE PRECISION NOT NULL, repeti
euh en fait c'est pas du down ça !

2022-06-15 09:01 UTC, sblondeau approved these changes

2022-06-15 09:01 UTC, merged